In [1]:
using Pkg
Pkg.activate(".")
# for pkg in ["HTTP", "JSON", "Distributions", "Random", "PrettyTables", "JLD"]
#     Pkg.add(pkg)
# end

#Pkg.instantiate()

  Activating project at `C:\Users\jbrig\Documents\research\mapinator_2024\notes\december_presentation`


In [2]:
using JSON, JLD

In [3]:
include("type_allocation_base_by_applicant_893.jl")

Main.SBM

In [4]:
to_from_by_year_api = SBM.fetch_data("to_from_by_year_mapinator_api.json")

Dict{String, Any} with 24 entries:
  "2009" => Dict{String, Any}("1886"=>Dict{String, Any}("disappeared"=>nothing,…
  "2018" => Dict{String, Any}("37196"=>Dict{String, Any}("disappeared"=>nothing…
  "2014" => Dict{String, Any}("55893"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2005" => Dict{String, Any}("11382"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2008" => Dict{String, Any}("3720"=>Dict{String, Any}("disappeared"=>0, "to_s…
  "2010" => Dict{String, Any}("5422"=>Dict{String, Any}("disappeared"=>nothing,…
  "2016" => Dict{String, Any}("29795"=>Dict{String, Any}("disappeared"=>nothing…
  "2019" => Dict{String, Any}("43054"=>Dict{String, Any}("disappeared"=>nothing…
  "2004" => Dict{String, Any}("24943"=>Dict{String, Any}("disappeared"=>nothing…
  "2026" => Dict{String, Any}("61387"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2023" => Dict{String, Any}("56205"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2007" => Dict{String, Any}("24350"=>Dict{String, Any}("disappeared"=>no

In [5]:
by_year_893 = SBM.fetch_data("to_from_by_year_893_mapinator_api.json")

Dict{String, Any} with 21 entries:
  "2014" => Dict{String, Any}("21269"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2018" => Dict{String, Any}("30648"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2005" => Dict{String, Any}("52068"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2008" => Dict{String, Any}("13775"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2010" => Dict{String, Any}("1495"=>Dict{String, Any}("disappeared"=>0, "to_s…
  "2016" => Dict{String, Any}("27274"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2019" => Dict{String, Any}("42525"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2007" => Dict{String, Any}("32"=>Dict{String, Any}("disappeared"=>0, "to_sho…
  "2023" => Dict{String, Any}("41022"=>Dict{String, Any}("disappeared"=>1, "to_…
  "2017" => Dict{String, Any}("40521"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2022" => Dict{String, Any}("54879"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2021" => Dict{String, Any}("48346"=>Dict{String, Any}("disappeared"=>0,

In [6]:
included_years = [parse(Int, year) for year in keys(to_from_by_year_api)]
# auto-detect year interval; change this to select the years of data to include in the estimation
YEAR_INTERVAL = minimum(included_years):maximum(included_years)

2003:2026

In [7]:
by_year_893_api = Dict()
for key in YEAR_INTERVAL
    if string(key) in keys(by_year_893)
        by_year_893_api[string(key)] = by_year_893[string(key)]
    end
end
by_year_893_api

Dict{Any, Any} with 20 entries:
  "2014" => Dict{String, Any}("21269"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2005" => Dict{String, Any}("52068"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2018" => Dict{String, Any}("30648"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2020" => Dict{String, Any}("51250"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2010" => Dict{String, Any}("1495"=>Dict{String, Any}("disappeared"=>0, "to_s…
  "2016" => Dict{String, Any}("27274"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2019" => Dict{String, Any}("42525"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2007" => Dict{String, Any}("32"=>Dict{String, Any}("disappeared"=>0, "to_sho…
  "2023" => Dict{String, Any}("41022"=>Dict{String, Any}("disappeared"=>1, "to_…
  "2017" => Dict{String, Any}("40521"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2022" => Dict{String, Any}("54879"=>Dict{String, Any}("disappeared"=>0, "to_…
  "2021" => Dict{String, Any}("48346"=>Dict{String, Any}("disappeared"=>0, "t

In [8]:
successful_applicant_outcome_years = Dict()
for year in keys(to_from_by_year_api)
    if parse(Int32, year) in YEAR_INTERVAL
        # ASSUMPTION: every applicant ID has only one placement
        for (applicant_id, placement) in to_from_by_year_api[year]
            if applicant_id in keys(successful_applicant_outcome_years)
                println("ERROR: applicant $(applicant_id) seen multiple times in dataset")
            end
            successful_applicant_outcome_years[applicant_id] = parse(Int32, year)
        end
    end
end

successful_applicant_outcome_years

Dict{Any, Any} with 14742 entries:
  "43399" => 2020
  "45445" => 2020
  "48189" => 2018
  "43935" => 2014
  "53230" => 2023
  "50675" => 2021
  "42410" => 2019
  "47359" => 2019
  "49576" => 2021
  "61935" => 2025
  "48877" => 2022
  "24363" => 2003
  "36678" => 2019
  "58038" => 2023
  "57052" => 2023
  "44924" => 2020
  "52234" => 2021
  "42792" => 2020
  "46555" => 2021
  "50070" => 2021
  "45204" => 2013
  "8603"  => 2011
  "7529"  => 2011
  "28215" => 2004
  "30875" => 2016
  ⋮       => ⋮

In [9]:
applicant_mapping, department_mapping, applicant_list, department_list, academic, academic_to, academic_builder, rough_sink_builder, department_name_mapping, reverse_mapping, applicant_department_mapping = SBM.get_builders(to_from_by_year_api, YEAR_INTERVAL);

In [10]:
# sink of teaching universities that do not graduate PhDs
# this must be constructed using academic placements, not pre-defined sink placements

teaching_universities = Set() 
for dept_name in academic_to
    if !(dept_name in academic)
        # the department hired an assistant professor but never graduated anyone
        push!(teaching_universities, dept_name)
    end
end

In [11]:
public_sector = ("Public Sector", Set())
private_sector = ("Private Sector", Set())
other_groups = ("Other Groups", Set())

postdocs = ("Postdocs", Set())
lecturers = ("Lecturers", Set())
other_academic = ("Other Academic", Set())

for outcome in rough_sink_builder
    if outcome["recruiter_type"] == 5 # government institution
        push!(public_sector[2], (string(outcome["to_name"], " ($(public_sector[1]))"), outcome))
    elseif outcome["recruiter_type"] in [6, 7] # private sector: for and not for profit
        push!(private_sector[2], (string(outcome["to_name"], " ($(private_sector[1]))"), outcome))
    elseif outcome["recruiter_type"] == 8 # international organizations, think tanks, assorted
        push!(other_groups[2], (string(outcome["to_name"], " ($(other_groups[1]))"), outcome))

    # some other examples
    # every example here must also have a corresponding sink Set() above, 
    #     and an entry in sinks_to_include below
   
    elseif outcome["postype"] == 6
        # postdocs that are not in the above (i.e. academic; not public, private, or other)
        # requires reconfiguration of the to_from_by_year loading code
        push!(postdocs[2], (string(outcome["to_name"], " ($(postdocs[1]))"), outcome))
    elseif outcome["postype"] in [5, 7]
        # lecturers that are not in the above
        # requires reconfiguration of the to_from_by_year loading code
        push!(lecturers[2], (string(outcome["to_name"], " ($(lecturers[1]))"), outcome))
    else
        # everything else including terminal academic positions
        # this sink can only be constructed as an "else" statement
        push!(other_academic[2], (string(outcome["to_name"], " ($(other_academic[1]))"), outcome))
    
    end
end

# TODO: if not including a sink results in a department/applicant having zero placements, should it still be included in the adjacency matrix?
# if we know a department exists but has no placements, is this part of the network structure? 
# removing the department means the department does not exist in the network

# sort to ensure consistent ordering
academic_list = sort(collect(academic))
teaching_list = sort(collect(teaching_universities))
# to be consistent with the original estimation, we only include these additional sinks:
sinks_to_include = (public_sector, private_sector, other_groups, lecturers)#, postdocs, lecturers, other_academic)

sink_mapping, sink_list, sink_builder, sinks, sink_labels = SBM.build_sinks(sinks_to_include, teaching_list)

NUMBER_OF_SINKS = length(sink_labels)
institutions = vcat(academic_list, sinks...)
println("$(length(academic_list)) academic departments, $(length(institutions)) total departments")

Including the following sinks:
 Public Sector
 Private Sector
 Other Groups
 Lecturers
 Teaching Universities
Total 5 sinks
1821 academic departments, 3932 total departments


In [12]:
length(academic_builder) + length(sink_builder)

13404

In [13]:
type_allocation_data = JSON.parsefile("id_to_type_api.json")

1181-element Vector{Any}:
 Dict{String, Any}("name" => "Aalborg University", "institution_id" => "1272", "type" => 4)
 Dict{String, Any}("name" => "Aalto University", "institution_id" => "332", "type" => 3)
 Dict{String, Any}("name" => "Aarhus University", "institution_id" => "206", "type" => 3)
 Dict{String, Any}("name" => "Abubakar Tafawa Balewa University", "institution_id" => "4640", "type" => 5)
 Dict{String, Any}("name" => "Academy of Postgraduate Education (Академия последипломного образования)", "institution_id" => "3656", "type" => 5)
 Dict{String, Any}("name" => "Accra Institute of Technology", "institution_id" => "6902", "type" => 5)
 Dict{String, Any}("name" => "Acharya Nagarjuna University", "institution_id" => "4432", "type" => 5)
 Dict{String, Any}("name" => "Adam Mickiewicz University, Poznań", "institution_id" => "3855", "type" => 5)
 Dict{String, Any}("name" => "Adnan Menderes University", "institution_id" => "2374", "type" => 5)
 Dict{String, Any}("name" => "Agricult

In [14]:
type_allocation_dict = Dict()
max_tier = 0
for entry in type_allocation_data
    if entry["type"] > max_tier
        max_tier = entry["type"]
    end
    type_allocation_dict[entry["institution_id"]] = entry["type"]
end
println("max tier: ", max_tier)
NUMBER_OF_TYPES = max_tier
numtotal = NUMBER_OF_TYPES + NUMBER_OF_SINKS
type_allocation_dict

max tier: 5


Dict{Any, Any} with 1181 entries:
  "1"    => 2
  "2243" => 5
  "5762" => 5
  "1881" => 5
  "4743" => 5
  "491"  => 3
  "332"  => 3
  "6264" => 5
  "1894" => 4
  "2579" => 5
  "2696" => 5
  "4699" => 5
  "2394" => 5
  "2366" => 4
  "3823" => 5
  "416"  => 4
  "23"   => 3
  "2631" => 5
  "2527" => 5
  "815"  => 4
  "1588" => 4
  "39"   => 4
  "2723" => 5
  "112"  => 4
  "791"  => 4
  ⋮      => ⋮

In [15]:
sink_labels

5-element Vector{Any}:
 "Public Sector"
 "Private Sector"
 "Other Groups"
 "Lecturers"
 "Teaching Universities"

In [16]:
outcome_counter = 0
placement_matrix = zeros(Int64, numtotal, NUMBER_OF_TYPES)
successful_tier_1 = 0
successful_tier_1_range = 2018:2023
for (applicant_id, outcome) in academic_builder
    outcome_to_name = string(outcome["to_name"], " - ", outcome["to_department"])
    if !(string(outcome["from_institution_id"]) in keys(type_allocation_dict))
        println("missing from_institution ", string(outcome["from_institution_id"]), " ", outcome["from_institution_name"], ", skipping outcome")
        continue
    end
    from_tier = type_allocation_dict[string(outcome["from_institution_id"])]
    if !(outcome_to_name in academic)
        outcome_counter += 1
        sink_tier = numtotal
        if ((from_tier == 1) && (successful_applicant_outcome_years[applicant_id] in successful_tier_1_range))
            successful_tier_1 += 1
        end
        placement_matrix[sink_tier, from_tier] += 1
    else
        if !(string(outcome["to_institution_id"]) in keys(type_allocation_dict))
            println("missing to_institution ", string(outcome["to_institution_id"]), " ", outcome_to_name, ", skipping outcome")
            continue
        end
        outcome_counter += 1
        if ((from_tier == 1) && (successful_applicant_outcome_years[applicant_id] in successful_tier_1_range))
            successful_tier_1 += 1
        end
        placement_matrix[type_allocation_dict[string(outcome["to_institution_id"])], from_tier] += 1
    end
end
for (outcome_to_name, outcome) in sink_builder
    if !(string(outcome["from_institution_id"]) in keys(type_allocation_dict))
        println("missing from_institution ", string(outcome["from_institution_id"]), " ", outcome["from_institution_name"], ", skipping outcome")
        continue
    end
    outcome_counter += 1
    if occursin(" (Public Sector)", outcome_to_name)
        sink_tier = NUMBER_OF_TYPES + 1
    elseif occursin(" (Private Sector)", outcome_to_name)
        sink_tier = NUMBER_OF_TYPES + 2
    elseif occursin(" (Other Groups)", outcome_to_name)
        sink_tier = NUMBER_OF_TYPES + 3
    elseif occursin(" (Lecturers)", outcome_to_name)
        sink_tier = NUMBER_OF_TYPES + 4
    else
        println("INVALID SINK DETECTED")
    end
    from_tier = type_allocation_dict[string(outcome["from_institution_id"])]
    if ((from_tier == 1) && (successful_applicant_outcome_years[outcome["aid"]] in successful_tier_1_range))
        successful_tier_1 += 1
    end
    placement_matrix[sink_tier, from_tier] += 1
end
println("outcomes: ", outcome_counter, " ", sum(placement_matrix))
placement_matrix

missing from_institution 754 Ocean and Crow Studios Inc, skipping outcome
outcomes: 13403 13403


10×5 Matrix{Int64}:
 761  115   41    8    0
 879  569  148   48    4
 839  993  443   60   14
 176  306  217  140   11
   3   14   16   15   46
 582  596  301   79   19
 700  438  244   68   24
 218  187  114   39    9
 165  244  315  201  104
 676  967  815  309  123

In [17]:
unmatched = zeros(Int, NUMBER_OF_TYPES)

for year in keys(by_year_893_api)
    if parse(Int32, year) in YEAR_INTERVAL
        # ASSUMPTION: every applicant ID has only one placement
        for (applicant_id, outcome) in by_year_893_api[year]
            if string(outcome["from_institution_id"]) in keys(type_allocation_dict)
                from_tier = type_allocation_dict[string(outcome["from_institution_id"])]
                unmatched[from_tier] += 1
            end
        end
    end
end

println(unmatched)

[300, 544, 667, 364, 273]


In [18]:
successful_tier_1

2098

### Compute the number of successful graduates in Tier 1 from 2018 to 2023

In [19]:
save("placement_matrices.jld", "placement_matrix", placement_matrix, "unmatched", unmatched, "successful_tier_1", successful_tier_1, "successful_tier_1_range", successful_tier_1_range)